#!/usr/bin/lua

local site = require 'gluon.site_config'
local users = require 'gluon.users'
local util = require 'gluon.util'

local uci = require('luci.model.uci').cursor()
local lutil = require 'luci.util'

-- Stuff that is done by both fastd and tunneldigger (in upgrade/400-*). Make sure we know what happens.
-- The simple-tc of the two does the same, so we don't mind. tunneldigger will probably tkae precedence
-- because "t" follows "f" in the alphabet.
uci:section('network', 'interface', 'mesh_vpn',
	  {
		  ifname = 'mesh-vpn',
		  proto = 'batadv',
		  mesh = 'bat0',
		  mesh_no_rebroadcast = 1,
		  mtu = site.tunneldigger_mesh_vpn.mtu,
		  macaddr = util.generate_mac(4, 0),
	  }
)

uci:save('network')
uci:commit('network')

uci:section('firewall', 'include', 'mesh_vpn_dns',
	  {
	    type = 'restore',
	    path = '/lib/gluon/dual-vpn/iptables.rules',
	    family = 'ipv4',
	  }
)

uci:save('firewall')
uci:commit('firewall')
